
<!--- 
This report display a listing table for a dataset and variables of interest.

Input parameters:
 
* Report-specific:
- reportTitle: string with report title
- reportTitleLevel: integer with level of the report title, 1 for chapter, 2 for section, ...
- dataFileName: string with name of the file of interest
- dataProcessing (optional): list with parameters for data processing, see ? medicalMonitoring::processData
- tableParams: list with any parameters for the table, see ? medicalMonitoring::tableMonitoring
(besides data/labelVars/pathVar/pathLab)
- comparisonTableType (optional): string with type of comparison table, either: 'none' (by default), 'newData-diff-interactive' or 'table-comparison-interactive'
- comparisonTableParams (optional): list with parameters for the comparison table, see ? glpgUtilityFct::compareTables
- loopingVar (optional): character vector with variables to loop over, a listing will be created for each combination of groups of this variable
- loopingNMax (optional): integer with maximal number of groups to consider (all by default)

* General:
- pathDataFolder: string with path to the data folder
- pathDataFolderOld (optional): string with path to the folder for old data
- patientProfilePath: string with relative path where patient profiles are stored

-->


```{r listingTemplate-options, echo = FALSE, warning = FALSE, message = FALSE}

library(knitr)
knitr::opts_chunk$set(
	echo = FALSE, 
	warning = FALSE, error = FALSE, message = FALSE, 
	results = "asis"
)

knitr::knit_hooks$set(
	message = function(x, options) {
		paste('\n\n<div class="alert alert-info">',
			gsub('##', '\n', x),
			'</div>', sep = '\n')
	}
)

# print warnings where they occur (warn = 0 by default)
options(warn = 1)

```

```{r listingTemplate-attachParameters}

attach(params)

if(!exists("comparisonTableType"))	comparisonTableType <- "none"
if(comparisonTableType != "none" & 
	(!exists("pathDataFolderOld") || !file.exists(file.path(pathDataFolderOld, dataFileName)))
){
	warning("No comparison table is included because data from previous batch is not available.")
	comparisonTableType <- "none"
}

if(!exists("patientProfilePath"))	patientProfilePath <- NULL
if(!exists("loopingVar")) loopingVar <- NULL
if(!exists("loopingTotal"))	loopingTotal <- TRUE

```

```{r listingTemplate-loadPackages}

library(glpgUtilityFct)
library(inTextSummaryTable)
library(medicalMonitoring)
library(plyr)

```

```{r listingTemplate-setTitle}

if(!exists("reportTitleLevel"))	reportTitleLevel <- 1

# Create a header at the wanted depth
cat(getMdHeader(title = reportTitle, level = reportTitleLevel))

```

```{r listingTemplate-getData}

if(comparisonTableType != "none") {
	
	pathsData <- c(
		"currentData" = pathDataFolder,
		"previousData" = pathDataFolderOld
	)	
	
} else pathsData <- c("currentData" = pathDataFolder)

dataList <- sapply(names(pathsData), function(dataBatch) {
			
	# Load data
	pathData <- file.path(pathsData[[dataBatch]], dataFileName)
	
	dataAll <- loadDataADaMSDTM(pathData, verbose = FALSE)
	data <- dataAll[[1]]
	
	# Extract label information
	labelVars <- attr(dataAll, "labelVars")
	
	# Data processing 
	if(exists("dataProcessing")){
		data <- processData(
			data = data, 
			dataPath = pathDataFolder,
			processing = dataProcessing,
			verbose = TRUE,
			labelVars = labelVars
		)
		# Labels updated with extra annotation:
		labelVars <- attr(data, "labelVars")
	}
	
	# Create URL to patient profiles
	if(!is.null(patientProfilePath))
		data <- createPatientProfileVar(
			data = data, 
			patientProfilePath = patientProfilePath,
			checkExist = FALSE
		)
	
	# only subset of the data if requested
	if(!is.null(loopingVar) && exists("loopingNMax") &&	is.integer(loopingNMax)){
		
		data <- merge(
			x = data,
			y = unique(data[, loopingVar, drop = FALSE])[seq_len(loopingNMax), , drop = FALSE],
			all = FALSE
		)
		
	}
	
    attr(data, "labelVars") <- labelVars
	data
	
}, simplify = FALSE)

dataPrevious <- dataList$previousData
dataCurrent <- dataList$currentData
labelVars <- attr(dataCurrent, "labelVars")

```

```{r listingTemplate-getListingTable, eval = (comparisonTableType  == "none"), message = TRUE}	

data <- dlply(dataCurrent, loopingVar, function(dataCurrentI){
			
	argsTable <- c(
		list(
			data = dataCurrentI, 
			labelVars = labelVars,
			pathVar = if(!is.null(patientProfilePath))	"patientProfilePath",
			pathLab = labelVars["USUBJID"]
		),
		tableParams
	)
	do.call("tableMonitoring", argsTable)
	
})

knitPrintMedicalMonitoring(data, level = reportTitleLevel + 1)

```

```{r listingTemplate-getListingComparisonTable, eval = (comparisonTableType %in% c("newData-diff-interactive", "table-comparison-interactive")), message = TRUE}	

data <- dlply(dataCurrent, loopingVar, function(dataCurrentI){

	# get comparison table
	if(!is.null(loopingVar)){
		dataPreviousI <- merge(
			x = unique(dataCurrentI[, loopingVar, drop = FALSE]),
			y = dataPrevious,
			by = loopingVar,
			all = FALSE
		)
	}else	dataPreviousI <- dataPrevious

	## create data.frame with differences:
	
	# input parameters for compareTables function:
	argsCompTable <- comparisonTableParams
	
	switch(comparisonTableType, 
			
		`newData-diff-interactive` = {
			
			argsCompTable$outputType <- "newData-diff-interactive"
			
			# set columns to labels (if available)
			if(!is.null(labelVars))
				argsCompTable$colnames <- setNames(names(labelVars), labelVars)
			
			# add patientProfileLink at the column position of USUBJID
			if(!is.null(patientProfilePath)){
				
				idxColPPLink <- match("patientProfileLink", colnames(dataCurrentI))
				idxColUSUBJID <- match("USUBJID", colnames(dataCurrentI))
				idxColsSorted <- union(c(seq_len(idxColUSUBJID), idxColPPLink), seq_len(ncol(dataCurrentI)))
				dataCurrentI <- dataCurrentI[, idxColsSorted]
				
				argsCompTable$escape <- idxColUSUBJID 
				
				if(!is.null(labelVars))
					argsCompTable$colnames <- c(argsCompTable$colnames,
						setNames("patientProfileLink", getLabelVar(var = "USUBJID", labelVars = labelVars))
					)
				
			}
			
			argsCompTable$newData <- dataCurrentI
			argsCompTable$oldData <- dataPreviousI
			argsCompTable$nonVisibleVar <- c("USUBJID", "patientProfilesPath")
			tableComparisonDT <- do.call(compareTables, argsCompTable)
			
		},
		
		`table-comparison-interactive` = {
			
			# extract comparison table
			argsCompTable$newData <- dataCurrentI
			argsCompTable$oldData <- dataPreviousI
			argsCompTable$outputType <- "table-comparison"
			tableComparison <- do.call(compareTables, argsCompTable)
			
			# add patient profiles to diff table:
			if(!is.null(patientProfilePath))
				tableComparison$USUBJID <- dataCurrentI[
					match(tableComparison$USUBJID, dataCurrentI$USUBJID),
					"patientProfileLink"
				]
			
			# export to DT
			argsExportDiff <- list(diffData = tableComparison)			
			
			# set columns to labels (if available)
			if(!is.null(labelVars))
				argsExportDiff$colnames <- setNames(names(labelVars), labelVars)
			
			# escape this column
			argsExportDiff$escape <- match("USUBJID", colnames(tableComparison))-1
			
			tableComparisonDT <- do.call(exportDiffData, argsExportDiff)
			
		}
		
	)

	tableComparisonDT <- do.call(exportDiffData, argsExportDiff)
	
})

knitPrintMedicalMonitoring(data, level = reportTitleLevel + 1)

```