---
title: "Patient profiles"
subtitle: "`r paste(c(if(!is.null(params$study)){paste('Study:', params$study)}, if(!is.null(params$batch)){paste('Batch:', params$batch)}), collapse = '<br>')`"
author: "`r params$author`"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
params:
  dataPath:
  outputFile: './patientProfiles/subjectProfile.pdf' 
  author: ''
  batch: ''
  study: ''
  subsetDataset: NULL
  subsetVar: NULL
  subsetValue: NULL
  subsetSample: NULL
  subjectSortDataset: NULL
  subjectSortVar: NULL
  subjectSortDecreasing: FALSE
  exportBatchSize: 5
output:
  glpgStyle::html_report: default
---

<!-- All the chunks are prepended with 'patientProfiles-' to ensure chunk -->
<!-- labels are unique if this report is created within another Rmd document -->
<!-- (otherwise: issue might encounter error: 'duplicated label ...') -->

```{r patientProfiles-runDocument-example, eval = FALSE}

	dataPath <- "/home/lcougnaud/git/GLPGSAPCysticFibrosis/data/GLPG1972/GLPG1972-CL-201/DM010 SDTM locked DB/DSMB Snapshots/20191023_transfer12/SAS_Datasets"
	outputFile <- file.path("../MOMP", "patientProfiles", "subjectProfile.pdf")
	
	# run report:
	rm(params)
	
	# run report for 5 random randomized patients
	rmarkdown::render(
		input = "patientProfiles.Rmd",
		params = list(
			dataPath = dataPath,
			outputFile = outputFile,
			study = "Roccella",
			batch = "20191023 (transfer12)",
			author = "Laure Cougnaud",
			subsetDataset = "DS",
			subsetVar = "DSDECOD",
			subsetValue = "RANDOMIZED",
			subsetSample = 5
		)
	)
	
	# run report for patients with adverse events with toxicity grade >= 4
	rmarkdown::render(
		input = "patientProfiles.Rmd",
		params = list(
			dataPath = dataPath,
			outputFile = outputFile,
			study = "Roccella",
			batch = "20191023 (transfer12)",
			author = "Laure Cougnaud",
			subsetDataset = "AE",
			subsetVar = "AETOXGR",
			subsetValue = 4:5
		)
	)
	
```

# Patient profiles

```{r patientProfiles-optionsChunks, echo = FALSE, cache = FALSE}

	library(knitr)

	knitr::opts_chunk$set(
		# don't print code in the report
		echo = FALSE, 
		message = TRUE,
		# stop document execution if error (not the default)
		error = FALSE, # stop-on-error
		fig.align = "center",
		warning = FALSE,
		# to have list of DT included within a chunk with: glpgUtilityFct::knitPrintListObjects
		results = 'asis'
	)
	
```

```{r patientProfiles-loadPackages}

	library(patientProfilesVis)

```

```{r patientProfiles-loadData}

	library(glpgUtilityFct)

	pathFiles <- list.files(path = params$dataPath, pattern = "*.sas7bdat$", full.names = TRUE)
	
	if(length(pathFiles) == 0)
		stop(paste0("No data is available in:", params$dataPath, "."))
	
	# this step is time-consuming:
	tmp <- system.time(dataAll <- loadDataADaMSDTM(files = pathFiles))# 25s
	labelVars <- attr(dataAll, "labelVars")

```

```{r patientProfiles-palettes}

	library(glpgStyle)
	colorPalette <- glpgColor(c("main", "extra", "highlight"))

	# In ADaM-like format, date flag variables are formatted as following:
	shapePaletteDateFlag <- c(
		Complete = '\u25A0', Partial = '\u25CF', 
		`Missing start` = "\u25C0", `Missing end` = "\u25B6"
	)
	# convert date-flag variable to factor and returm warning if extra elements are present
	formatDateFlagVar <- function(x, type = c("start", "end")){
		type <- match.arg(type)
		# empty records should already be replaced by: 'Complete' in ADaM-like format
		idxEmpty <- which(x == "")
		x[idxEmpty] <- "Complete"
		levels <- names(shapePaletteDateFlag)
		palette <- shapePaletteDateFlag
		# add extra elements if present
		xExtra <- setdiff(unique(x), names(shapePaletteDateFlag))
		if(length(xExtra) > 0){
			warning("Flag variable contain non-standard elements:", toString(xExtra), ".")
			levels <- c(levels, xExtra)
			palette <- c(palette, setNames(seq_along(xExtra), xExtra))
		}
		xFact <- factor(x, levels = levels)
		return(list(x = xFact, palette = palette))
	}
	
	# color/shape palette for reference range indicator (abnormality lab/vs)
	shapePaletteRind <- c(
		`Low Panic` = '\u25BC', # big filled up-pointing arrow
		LOW = '\u25BC', Low = '\u25BC', # filled down-pointing arrow
		`Low Normal` = '\u25BC', # small filled down-pointing arrow
		NORMAL = '\u25CF', Normal = '\u25CF', # filled circle
		`High Normal` = '\u25B2', # small filled up-pointing arrow
		HIGH = '\u25B2', High = '\u25B2', # filled up-pointing arrow
		`High Panic` = '\u25B2', # big filled up-pointing arrow
		Abnormal = '\u2605', # star
		'NA' = '\u271A', # cross (3)
		Unknown = '\u271A'
	)
	colorPaletteRind <- c(
		`Low Panic` = unname(colorPalette["signalRed"]),
		LOW = unname(colorPalette["orange"]), Low = unname(colorPalette["orange"]),
		`Low Normal` = unname(colorPalette["yellow"]),
		NORMAL = unname(colorPalette["green"]), Normal = unname(colorPalette["green"]),
		`High Normal` = unname(colorPalette["yellow"]),
		HIGH = unname(colorPalette["orange"]), High = unname(colorPalette["orange"]),
		`High Panic` = unname(colorPalette["signalRed"]),
		Abnormal = unname(colorPalette["signalRed"]),
		'NA' = unname(colorPalette["grey"]),
		Unknown = unname(colorPalette["grey"])
	)

```

```{r patientProfiles-subsetData}	
	
	# extract the subjects of interest for the visualization
	subjectSubset <- NULL
	if(!is.null(params$subsetDataset)){
		if(params$subsetDataset %in% names(dataAll)){
			dataSubset <- dataAll[[params$subsetDataset]]
			if(!is.null(params$subsetVar) & !is.null(params$subsetValue) &&
				params$subsetVar %in% colnames(dataSubset)){
				dataSubset <- dataSubset[which(
					dataSubset[, params$subsetVar] %in% params$subsetValue
				), ]
			}
			subjectSubset <- unique(dataSubset$USUBJID)
			if(!is.null(params$subsetSample) && length(params$subsetSample) < length(subjectSubset)){
				subjectSubset <- sample(x = subjectSubset, size = params$subsetSample)
			}
		}else{
			warning(paste("The specified data subset is not used because the",
				params$subsetDataset, "dataset not available."))
		}
	}
	
```

```{r patientProfiles-initialization}

	patientProfileModules <- c()
	patientProfilesPlots <- list()

```

## Demographics

```{r patientProfiles-formatData-DM, eval = any(c("DM", "ADSL") %in% names(dataAll))}

	## define datasets and variables of interest:
	
	## demographic data
	
	dataDMName <- c(SDTM = "DM", ADaM = "ADSL")
	dataDMName <- dataDMName[dataDMName %in% names(dataAll)]
	
	# data manipulation
	dataDM <- dataAll[[dataDMName]]
	
	# input parameters
	# -> you might include variables with (study-specific) baseline characteristics
	varsDM <- c(
		"ASEX", "SEX", 
		"ARACE", "RACE", "CNTRY", 
		"COUNTRY", 
		"ETHNIC", "AETHNIC",
		"SITEID", 
		"AGE", "AAGE", "RFSTDTC"
	)
	varsDM <- intersect(varsDM, colnames(dataDM))
	# remove 'var' if 'A[var]' is already present (e.g. AAGE is considered if AAGE and AGE both present)
	varsDM <- varsDM[!paste0("A", varsDM) %in% varsDM]
	
	if("COUNTRY" %in% varsDM){
		library(countrycode)
		dataDM[, "COUNTRY"] <- countrycode(
			sourcevar = dataDM[, "COUNTRY"], 
			origin = "iso3c",
			destination = "country.name"
		)
	}
	if("SEX" %in% varsDM){
		dataDM[, "SEX"] <- with(dataDM,
			ifelse(SEX %in% c("M", "F", "U"), c(M = "Male", F = "Female", U = "Unknown")[SEX], SEX)
		)
	}
	
	if("ETHNIC" %in% varsDM)
		dataDM$ETHNIC <- simpleCap(tolower(dataDM$ETHNIC), onlyFirst = FALSE)
	
	if("RACE" %in% varsDM)
		dataDM$RACE <- simpleCap(tolower(dataDM$RACE), onlyFirst = FALSE)
	
	# Date of randomization
	# Study-specific baseline characteristics

	hasDMData <- !is.null(dataDM) && length(varsDM) > 0
	if(hasDMData)
		patientProfileModules <- c(patientProfileModules, "dm")

```

```{r patientProfiles-createPatientProfiles-dm, eval = "dm" %in% patientProfileModules}
	dmPlots <- subjectProfileTextPlot(
		data = dataDM,
		paramValueVar = varsDM,
		labelVars = labelVars,
		subjectSubset = subjectSubset
	)
	patientProfilesPlots <- c(patientProfilesPlots, list(DM = dmPlots))
```

## Medical history

```{r patientProfiles-formatData-MH, eval = any(c("ADMH", "MH") %in% names(dataAll))}

	## medical history
	
	dataMHName <- c(SDTM = "MH", ADaM = "ADMH")
	dataMHName <- dataMHName[dataMHName %in% names(dataAll)]
	
	# data manipulation
	dataMH <- dataAll[[dataMHName]]
	
	# variable with medical history term
	# MHTERM from CRF
	varMHCode <- intersect(c("ADECOD", "MHDECOD"), colnames(dataMH))[1]
	varMH <- if(length(varMHCode) > 0){
		idxEmptyCode <- which(dataMH[[varMHCode]] == "")
		if(length(idxEmptyCode) > 0){
			message(paste(length(idxEmptyCode), "empty", varMHCode, " are replaced by: 'MHTERM' or 'Unknown' is missing."))
			dataMH[idxEmptyCode, "MHDECOD"] <- if("MHTERM" %in% colnames(dataMH)){
				with(dataMH[idxEmptyCode, ], ifelse(MHTERM == "", "No MH term provided.", paste("(Not coded)", MHTERM)))
			}else	"Unknown"
		}
		varMHCode
	}else	if("MHTERM" %in% colnames(dataMH)){
		dataMH[, "MHTERM"] <- with(dataMH, ifelse(MHTERM == "", "No MH term provided.", MHTERM))
		"MHTERM"
	}
	
	# if empty start data: 'Unknown'
	varMHSTDT <- intersect(c("ASTDT", "MHSTDTC"), colnames(dataMH))[1]
	dataMH[which(dataMH[, varMHSTDT] == ""), varMHSTDT] <- "Unknown"
	
	# build end versus End Relative to Reference Period (MHENRF)
	varMHAENDT <- intersect(c("AENDT", "MHSTDTC"), colnames(dataMH))[1]
	dataMH[[varMHAENDT]] <- if(length(varMHAENDT) > 0){
		dataMH[which(dataMH[, varMHAENDT] == ""), varMHAENDT] <- "Unknown"
	}else "Unknown"
	dataMH[[varMHAENDT]] <- trimws(dataMH[[varMHAENDT]])
	
	# MHENRF: might be called differently MHENTPTRF
	mhEndRefVar <- "MHENRTPT"
	if(!mhEndRefVar %in% colnames(dataMH)){
		warning(sQuote(mhEndRefVar), " not available in your MH data, you might want to specify it yourself.")
	}else{	
		dataMH[[varMHAENDT]] <- paste0(
			dataMH[[varMHAENDT]],
			if(mhEndRefVar %in% colnames(dataMH))
				ifelse(dataMH[[mhEndRefVar]] != "", paste0(" (", tolower(dataMH[[mhEndRefVar]]), ")"), "")
		)
	}
	labelVars[c(varMHSTDT, varMHAENDT)] <- c(
		"Start", 
		paste0("End", if(mhEndRefVar %in% colnames(dataMH))
			paste0("\n(", labelVars[mhEndRefVar], ")")
		)
	)
	
	# issue for one character: '\xbd' of MHTERM
	dataMH[[varMH]] <- iconv(dataMH[[varMH]], from = "UTF-8", to = "Latin1", sub = '')
	if(any(is.na(dataMH$TERM)))	stop("Issue during conversion of MHTERM.")
	
	# input parameters:
	paramValueVarMH <- c(varMH, varMHSTDT, varMHAENDT)
	
	# MHBODSYS/MHSOC Only include this variable when MHTERM is coded using MedDRA
	paramGroupVarMH <- varMHSTDT
	
	hasMHData <- 
		!is.null(dataMH) && !is.null(varMH) && 
		length(paramValueVarMH) > 0 && length(paramGroupVarMH) > 0
	if(hasMHData){
		patientProfileModules <- c(patientProfileModules, "mh")
	}else{
		warning("Patient profiles not created for exposure data, because of missing variables.")
	}
	
```

```{r patientProfiles-createPatientProfiles-mh, eval = "mh" %in% patientProfileModules}
	
	mhPlots <- subjectProfileTextPlot(
		data = dataMH,
		paramValueVar = paramValueVarMH,
		paramGroupVar = paramGroupVarMH,
		title = "Medical history (Start - End)",
		labelVars = labelVars,
		table = TRUE,
		subjectSubset = subjectSubset
	)
	patientProfilesPlots <- c(patientProfilesPlots, list(MH = mhPlots))

```

## Concomitant medications

```{r patientProfiles-formatData-CM, eval = any(c("ADCM", "CM") %in% names(dataAll))}	
	
	## concomitant medications

	dataCMName <- c(SDTM = "CM", ADaM = "ADCM")
	dataCMName <- dataCMName[dataCMName %in% names(dataAll)]
	
	# data manipulation
	dataCM <- dataAll[[dataCMName]]
	
	# CMDECOD empty if CM term not in dictionary
	varCMCode <- intersect(c("ADECOD", "CMDECOD"), colnames(dataMH))[1]
	varCM <- if(length(varCMCode) > 0){
		idxEmptyCode <- which(dataCM[[varCMCode]] == "")
		if(length(idxEmptyCode) > 0){
			message(paste(length(idxEmptyCode), "empty CMDECOD are replaced by: 'CMTRT' or 'Unknown' is missing."))
			dataCM[idxEmptyCode, varCMCode] <- if("CMTRT" %in% names(dataCM)){
				with(dataCM[idxEmptyCode, ], ifelse(CMTRT == "", "Unknown", paste("(Not coded)", CMTRT)))
			}else	"Unknown"
		}
		varCMCode
	}else	if("CMTERM" %in% colnames(dataCM)){
		dataCM[, "CMTERM"] <- with(dataMH, ifelse(CMTERM == "", "No CM term provided.", CMTERM))
		"CMTERM"
	}

	if("CMDOSE" %in% colnames(dataCM))
		dataCM$CMDOSTXT <- prettyNum(dataCM$CMDOSE)
	
	colorVarCM <- if("CMCAT" %in% colnames(dataCM)){
		dataCM$CMCAT <- with(dataCM, ifelse(CMCAT == "", "Unknown", CMCAT))
		"CMCAT"
	}
	
	varCMInd <- intersect(c("AINDC", "CMINDC"), colnames(dataCM))[1]
	paramGroupVarCM <- if(length(varCMInd) > 0){
		idxCMIndEmpty <- which(dataCM[[varCMInd]] == "")
		dataCM[idxCMIndEmpty, varCMInd] <- "Unknown"
		varCMInd
	}
	
	# input parameters
	# When CMDOSU == "Other" -> CMDOSUO (free text from CRF)
	paramVarCM <- if("ADECODSP" %in% colnames(dataCM)){ 
		c("ADECODSP", "CMROUTE")
	}else	c(varCM, "CMDOSTXT", "CMDOSU", "CMDOSFRQ", "CMROUTE")
	paramVarCM <- intersect(paramVarCM, colnames(dataCM))
	
	# start/end variable
	timeStartVarCM <- intersect(c("ASTDY", "CMSTDY"), colnames(dataCM))[1]
	timeEndVarCM <- intersect(c("AENDY", "CMENDY"), colnames(dataCM))[1]
	
	# start/end flags variable
	if("ASTFLG" %in% colnames(dataCM)){
		timeStartShapeVarCM <- "ASTFLG"
		flRes <- formatDateFlagVar(x = dataCM[[timeStartShapeVarCM]], type = "start")
		dataCM[[timeStartShapeVarCM]] <- flRes$x
		shapePaletteCM <- flRes$palette
	}else	timeStartShapeVarCM <- shapePaletteCM <- NULL
	if("AENFLG" %in% colnames(dataCM)){
		timeEndShapeVarCM <- "AENFLG"
		flRes <- formatDateFlagVar(x = dataCM[[timeEndShapeVarCM]], type = "end")
		dataCM[[timeEndShapeVarCM]] <- flRes$x
		shapePaletteCM <- c(shapePaletteCM, flRes$palette[!names(flRes$palette) %in% names(shapePaletteCM)])
	}else	timeEndShapeVarCM <- NULL
	
	hasCMData <- 
		!is.null(dataCM) && !is.null(varCM) &&
		length(timeStartVarCM) > 0 && length(timeEndVarCM) > 0
	if(hasCMData){
		patientProfileModules <- c(patientProfileModules, "cm")
	}else{
		warning("Patient profiles not created for concomitant medication data, because of missing variables.")
	}
	
```

```{r patientProfiles-createPatientProfiles-cm, eval = "cm" %in% patientProfileModules}

	# missing start/end date are taken from 
	# the minimum/maximum start date across all concomitant
	# medications per subject
	library(ggplot2)
	cmPlots <- subjectProfileIntervalPlot(
		data = dataCM,
		paramVar = paramVarCM,
		paramGroupVar = paramGroupVarCM,
		timeStartVar = timeStartVarCM,
		timeStartShapeVar = timeStartShapeVarCM,
		timeEndVar = timeEndVarCM,
		timeEndShapeVar = timeEndShapeVarCM,
		colorVar = colorVarCM,
		labelVars = labelVars,
		title = "Concomitant medications",
		# To zoom in axis scale in study time frame
		# (to avoid scale is focused on negative pre-study time frame for CM)
		timeTrans = getTimeTrans(type = "asinh-neg"), 
		timeExpand = expand_scale(mult = 0.01),
		shapePalette = shapePaletteCM, shapeLab = "Date status", shapeSize = 4,
		timeAlign = FALSE,
		subjectSubset = subjectSubset,
		alpha = 0.8
	)
	patientProfilesPlots <- c(patientProfilesPlots, list(CM = cmPlots))

```


## Treatment exposure

```{r patientProfiles-formatData-EX, eval = any(c("ADEX", "EX") %in% names(dataAll))}	
	
	## exposure data
	
	dataEXName <- c(SDTM = "EX", ADaM = "ADEX")
	dataEXName <- dataEXName[dataEXName %in% names(dataAll)]
	
	# data manipulation

	dataEX <- dataAll[[dataEXName]]
	
	# ADaM-like:
	paramVarEX <- if("AVALC" %in% colnames(dataEX)){
		"AVALC"
	# SDTM:
	}else{
		c("EXDECOD", "EXROUTE", "EXDOSFRM", "EXDOSFRQ")
	}
	paramVarEX <- intersect(paramVarEX, colnames(dataEX))
	
	# The user might adapt for each own study (EXTRT)!! -> include warning
	colorVarEX <- if("EXDOSFRM" %in% colnames(dataEX))	"EXDOSFRM"
	
	# input parameters for the report:
	timeStartVarEX <- intersect(c("ASTDY", "EXSTDY"), colnames(dataEX))[1]
	timeEndVarEX <- intersect(c("AENDY", "EXENDY"), colnames(dataEX))[1]
	
	# start/end flags variable
	if("ASTFLG" %in% colnames(dataEX)){
		timeStartShapeVarEX <- "ASTFLG"
		flRes <- formatDateFlagVar(x = dataEX[[timeStartShapeVarEX]], type = "start")
		dataEX[[timeStartShapeVarEX]] <- flRes$x
		shapePaletteEX <- flRes$palette
	}else	timeStartShapeVarEX <- shapePaletteEX <- NULL
	if("AENFLG" %in% colnames(dataEX)){
		timeEndShapeVarEX <- "AENFLG"
		flRes <- formatDateFlagVar(x = dataEX[[timeEndShapeVarEX]], type = "end")
		dataEX[[timeEndShapeVarEX]] <- flRes$x
		shapePaletteEX <- c(shapePaletteEX, flRes$palette[!names(flRes$palette) %in% names(shapePaletteEX)])
	}else	timeEndShapeVarEX <- NULL
	
	hasEXData <- 
		!is.null(dataEX) && length(paramVarEX) > 0 && 
		length(timeStartVarEX) > 0 && length(timeEndVarEX) > 0
	if(hasEXData){
		patientProfileModules <- c(patientProfileModules, "ex")
	}else{
		warning("Patient profiles not created for exposure data, you might need to specify study-specific variables.")
	}
	
```

```{r patientProfiles-createPatientProfiles-ex, eval = "ex" %in% patientProfileModules}
	exPlots <- subjectProfileIntervalPlot(
		data = dataEX,
		paramVar = paramVarEX,
		timeStartVar = timeStartVarEX,
		timeStartShapeVar = timeStartShapeVarEX,
		timeEndVar = timeEndVarEX,
		timeEndShapeVar = timeEndShapeVarEX,
		colorVar = colorVarEX,
		shapePalette = shapePaletteEX, shapeLab = "Date status", shapeSize = 4,
		labelVars = labelVars,
		title = "Treatment exposure",
		timeAlign = FALSE,
		subjectSubset = subjectSubset,
		alpha = 0.8
	)
	patientProfilesPlots <- c(patientProfilesPlots, list(EX = exPlots))
```

## Adverse events

```{r patientProfiles-formatData-AE, eval = any(c("ADAE", "AE") %in% names(dataAll))}	
	
	## adverse event
	
	dataAEName <- c(SDTM = "AE", ADaM = "ADAE")
	dataAEName <- dataAEName[dataAEName %in% names(dataAll)]
	
	# data manipulation
	dataAE <- dataAll[[dataAEName]]
	
	# variable with adverse event term
	varAECode <- intersect(c("ADECOD", "AEDECOD"), colnames(dataAE))[1]
	paramVarAE <- if(length(varAECode) > 0){
		idxEmptyCode <- which(dataAE[[varAECode]] == "")
		if(length(idxEmptyCode)){
			message(paste(length(idxEmptyCode), "empty", varAECode, "are replaced by: 'AETERM' or 'Unknown' is missing."))
			dataAE[idxEmptyCode, varAECode] <- if("AETERM" %in% colnames(dataAE)){
				with(dataAE[idxEmptyCode, ], ifelse(AETERM == "", "No AE term available.", AETERM))
			}else	"Unknown"
		}
		varAECode
	}else	if("AETERM" %in% colnames(dataCM)){
		"AETERM"
	}

	# start/end variables
	timeStartVarAE <- intersect(c("ASTDY", "AESTDY"), colnames(dataAE))[1]
	timeEndVarAE <- intersect(c("AENDY", "AEENDY"), colnames(dataAE))[1]

	# start/end flags variable
	if("ASTFLG" %in% colnames(dataAE)){
		timeStartShapeVarAE <- "ASTFLG"
		flRes <- formatDateFlagVar(x = dataAE[[timeStartShapeVarAE]], type = "start")
		dataAE[[timeStartShapeVarAE]] <- flRes$x
		shapePaletteAE <- flRes$palette
	}else	timeStartShapeVarAE <- shapePaletteAE <- NULL
	if("AENFLG" %in% colnames(dataAE)){
		timeEndShapeVarAE <- "AENFLG"
		flRes <- formatDateFlagVar(x = dataAE[[timeEndShapeVarAE]], type = "end")
		dataAE[[timeEndShapeVarAE]] <- flRes$x
		shapePaletteAE <- c(shapePaletteAE, flRes$palette[!names(flRes$palette) %in% names(shapePaletteAE)])
	}else	timeEndShapeVarAE <- NULL
	
	# AESEV or AETOXGR: 1 -> 5 (CTCTAE), Mild/Moderate/Severe
	colorVarAE <- intersect(c("ASEV", "AETOXGR"), colnames(dataAE))[1]
	colorPaletteAE <- colorPalette[c("green", "sand", "yellow", "orange", "signalRed", "grey")]
	if(colorVarAE == "ASEV"){
		indLevels <- c("Mild", "Moderate", "Severe", "Life-threatening", "Fatal")
		dataAE[, colorVarAE] <- reorder(dataAE[, "ASEV"], dataAE[, "ASEVN"])
		dataAE[, colorVarAE] <- convertAesVar(dataAE, var = colorVarAE)
	}else	if(colorVarAE == "AETOXGR"){
		indLevels <- as.character(1:5)
		dataAE[, colorVarAE] <- convertAesVar(dataAE, var = colorVarAE)
	}
	if(length(colorVarAE) > 0){
		if(all(unique(dataAE[, colorVarAE]) %in% c(NA, "", indLevels))){
			# 1: mild, 2: moderate, 3: severe, 4: life-threatening/disable, 5: death-related to AE
			colorPaletteAE <- setNames(unname(colorPaletteAE), c(indLevels, "NA"))
			colorPaletteAE <- colorPaletteAE[names(colorPaletteAE) %in% c("NA", levels(dataAE[, colorVarAE]))]
		}else	warning(paste("Laboratory", labelVars[colorVarAE],
					"contain unexpected values, so standard color palette is not used."))
	}
	
	hasAEData <- 
		!is.null(dataAE) && 
		!is.null(paramVarAE) &&
		length(timeStartVarAE) > 0 && length(timeEndVarAE) > 0
	if(hasAEData){
		patientProfileModules <- c(patientProfileModules, "ae")
	}else{
		warning("Patient profiles not created for adverse events data, because of missing variables.")
	}
	
```

```{r patientProfiles-createPatientProfiles-ae, eval = "ae" %in% patientProfileModules}
	aePlots <- subjectProfileIntervalPlot(
		data = dataAE,
		paramVar = paramVarAE,
		timeStartVar = timeStartVarAE,
		timeStartShapeVar = timeStartShapeVarAE,
		timeEndVar = timeEndVarAE,
		timeEndShapeVar = timeEndShapeVarAE,
		colorVar = colorVarAE, colorPalette = colorPaletteAE,
		shapePalette = shapePaletteAE, shapeLab = "Date status", shapeSize = 4,
		labelVars = labelVars,
		title = "Adverse events",
		timeAlign = FALSE,
		subjectSubset = subjectSubset,
		alpha = 0.8
	)
	
	patientProfilesPlots <- c(patientProfilesPlots, list(AE = aePlots))
```

## Laboratory measurements

```{r patientProfiles-formatData-LB, eval = any(c("ADLB", "LB") %in% names(dataAll))}	
	
	# use spaghetti plot with symbols

	## laboratory data
	
	dataLBName <- c(SDTM = "LB", ADaM = "ADLB")
	dataLBName <- dataLBName[dataLBName %in% names(dataAll)]
	
	# data
	dataLB <- dataAll[[dataLBName]]
	
	# input parameters
	
	# unique LB is defined by LBTEST*LBSPEC*LBMETHOD
	# check if the extra variables are required:
	if("PARAM" %in% colnames(dataLB)){
		varsLB <- c("PARAM")
	}else{
		varsLB <- c("LBTEST", "LBSTRESU")
	}
	varsLB <- c(varsLB, "LBSPEC") # , "LBMETHOD"
	varsLB <- intersect(varsLB, colnames(dataLB))
	i <- 1
	while(i < length(varsLB)){
		nEl <- nrow(unique(dataLB[, varsLB[seq_len(i)], drop  = FALSE]))
		nElNext <- nrow(unique(dataLB[, varsLB[seq_len(i+1)]]))
		if(nEl == nElNext){
			varsLB <- setdiff(varsLB, varsLB[i+1])
		}else	i <- i + 1
	}
	
	paramValueVarLB <- intersect(c("AVAL", "LBSTRESN"), colnames(dataLB))[1]
	
	paramValueRangeVarLB <- intersect(c("LBSTNRLO", "LBSTNRHI"), colnames(dataLB))
	if(length(paramValueRangeVarLB) != 2)	paramValueRangeVarLB <- NULL
	
	paramVarLB <- varsLB
	timeVarLB <- intersect(c("ADY", "LBDY"), colnames(dataLB))[1]
	
	paramGroupVarLB <- intersect(c("LBCAT", "LBSCAT"), colnames(dataLB))
	if(length(paramGroupVarLB) == 0)	paramGroupVarLB <- NULL
	
	colorVarLB <- shapeVarLB <- intersect(c("ANRIND", "LBNRIND"), colnames(dataLB))[1]
	if(length(colorVarLB) > 0){
		
		idxEmpty <- which(dataLB[[colorVarLB]] == "")
		if(length(idxEmpty) > 0)
			dataLB[idxEmpty, colorVarLB] <- "Unknown"
		
		levels <- unique(dataLB[[colorVarLB]])
		# add extra elements if present
		xStandard <- intersect(names(colorPaletteRind), levels)
		xExtra <- setdiff(na.omit(levels), names(colorPaletteRind))
		if(length(xExtra) > 0)
			warning("Flag variable contain non-standard elements:", toString(xExtra), ".")
		levels <- c(xStandard, xExtra)
		shapePaletteLB <- c(shapePaletteRind[xStandard], setNames(seq_along(xExtra), xExtra))
		colorPaletteLB <- c(colorPaletteRind[xStandard], setNames(seq_along(xExtra), xExtra))
		dataLB[[colorVarLB]] <- factor(dataLB[[colorVarLB]], levels = levels)
		
	}else	colorVarLB <- shapeVarLB <- colorPaletteLB <- shapePaletteLB <- NULL
		
	hasLBData <- !is.null(dataLB) && 
		length(paramVarLB) > 0 && length(paramValueVarLB) > 0 &&
		length(timeVarLB) > 0
	if(hasLBData){
		patientProfileModules <- c(patientProfileModules, "lb")
	}else{
		warning("Patient profiles not created for laboratory data, because of missing variables.")
	}
	
```

```{r patientProfiles-createPatientProfiles-lb, eval = "lb" %in% patientProfileModules}
	lbPlots <- subjectProfileLinePlot(
		data = dataLB,
		paramValueVar = paramValueVarLB,
		paramNameVar = paramVarLB,
		paramValueRangeVar = paramValueRangeVarLB,
		paramGroupVar = paramGroupVarLB,
		timeVar = timeVarLB,
		colorVar = colorVarLB, colorPalette = colorPaletteLB,
		shapeVar = shapeVarLB, shapePalette = shapePaletteLB,
		shapeSize = 4,
		labelVars = labelVars,
		title = "Laboratory test measurements",
		subjectSubset = subjectSubset,
		alpha = 0.8
	)	
	patientProfilesPlots <- c(patientProfilesPlots, list(LB = lbPlots))
```

## Vital signs

```{r patientProfiles-formatData-VS, eval = any(c("ADVS", "VS") %in% names(dataAll))}	

	# use spaghetti plot with symbols

	## vital signs data
	
	dataVSName <- c(SDTM = "VS", ADaM = "ADVS")
	dataVSName <- dataVSName[dataVSName %in% names(dataAll)]
	
	# data
	dataVS <- dataAll[[dataVSName]]
	
	# input parameters
	
	# unique LB is defined by LBTEST*LBSPEC*LBMETHOD
	# check if the extra variables are required:
	if("PARAM" %in% colnames(dataVS)){
		varsVS <- "PARAM"
	}else{
		varsVS <- c("VSTEST", "VSSTRESU") # VSLOC, "VSPOS"
		varsVS <- intersect(varsVS, colnames(dataVS))
		i <- 1
		while(i < length(varsVS)){
			nEl <- nrow(unique(dataVS[, varsVS[seq_len(i)], drop  = FALSE]))
			nElNext <- nrow(unique(dataVS[, varsVS[seq_len(i+1)]]))
			if(nEl == nElNext){
				varsVS <- setdiff(varsVS, varsVS[i+1])
			}else	i <- i + 1
		}
	}
	
	paramValueVarVS <- intersect(c("AVAL", "VSSTRESN"), colnames(dataVS))[1]
	
	# ADaM-like: reference range as defined in SAP
	paramValueRangeVarVS <- intersect(c("ANRLO", "ANRHI"), colnames(dataVS))
	if(length(paramValueRangeVarVS) != 2)	paramValueRangeVarVS <- NULL
	
	paramVarVS <- varsVS
	timeVarVS <- intersect(c("ADY", "VSDY"), colnames(dataVS))[1]
	
	paramGroupVarVS <- intersect(c("VSCAT", "VSSCAT"), colnames(dataVS))
	if(length(paramGroupVarVS) == 0)	paramGroupVarVS <- NULL
	
	colorVarVS <- shapeVarVS <- intersect("ANRIND", colnames(dataVS))[1]
	if(length(colorVarVS) > 0){
		
		idxEmpty <- which(dataVS[[colorVarVS]] == "")
		if(length(idxEmpty) > 0)
			dataVS[idxEmpty, colorVarVS] <- "Unknown"
		levels <- unique(dataVS[[colorVarVS]])
		# add extra elements if present
		xStandard <- intersect(names(colorPaletteRind), levels)
		xExtra <- setdiff(na.omit(levels), names(colorPaletteRind))
		if(length(xExtra) > 0)
			warning("Flag variable contain non-standard elements:", toString(xExtra), ".")
		levels <- c(xStandard, xExtra)
		shapePaletteVS <- c(shapePaletteRind[xStandard], setNames(seq_along(xExtra), xExtra))
		colorPaletteVS <- c(colorPaletteRind[xStandard], setNames(seq_along(xExtra), xExtra))
		dataVS[[colorVarVS]] <- factor(dataVS[[colorVarVS]], levels = levels)
		
	}else	colorVarVS <- shapeVarVS <- colorPaletteVS <- shapePaletteVS <- NULL
		
	hasVSData <- !is.null(dataVS) && 
		length(paramVarVS) > 0 && length(paramValueVarVS) > 0 &&
		length(timeVarVS) > 0
	if(hasVSData){
		patientProfileModules <- c(patientProfileModules, "vs")
	}else{
		warning("Patient profiles not created for vital signs, because of missing variables.")
	}
	
```

```{r patientProfiles-createPatientProfiles-vs, eval = "vs" %in% patientProfileModules}
	vsPlots <- subjectProfileLinePlot(
		data = dataVS,
		paramValueVar = paramValueVarVS,
		paramNameVar = paramVarVS,
		paramValueRangeVar = paramValueRangeVarVS,
		paramGroupVar = paramGroupVarVS,
		timeVar = timeVarVS,
		colorVar = colorVarVS, colorPalette = colorPaletteVS,
		shapeVar = shapeVarVS, shapePalette = shapePaletteVS,
		shapeSize = 4,
		labelVars = labelVars,
		title = "Vital signs",
		subjectSubset = subjectSubset,
		alpha = 0.8
	)
	patientProfilesPlots <- c(patientProfilesPlots, list(VS = vsPlots))
```

## Electrocardiogram

```{r patientProfiles-formatData-EG, eval = any(c("ADEG", "EG") %in% names(dataAll))}	

	# use spaghetti plot with symbols

	## ECG data
	
	dataEGName <- c(SDTM = "EG", ADaM = "ADEG")
	dataEGName <- dataEGName[dataEGName %in% names(dataAll)]
	
	# data
	dataEG <- dataAll[[dataEGName]]
	
	# input parameters
	
	if("PARAM" %in% colnames(dataEG)){
		varsEG <- "PARAM"
	}else{
		varsEG <- c("EGTEST", "EGPOS", "EGSTRESU")
		varsEG <- intersect(varsEG, colnames(dataEG))
		i <- 1
		while(i < length(varsEG)){
			nEl <- nrow(unique(dataEG[, varsEG[seq_len(i)], drop  = FALSE]))
			nElNext <- nrow(unique(dataEG[, varsEG[seq_len(i+1)]]))
			if(nEl == nElNext){
				varsEG <- setdiff(varsEG, varsEG[i+1])
			}else	i <- i + 1
		}
	}
	
	paramValueVarEG <- intersect(c("AVAL", "EGSTRESN"), colnames(dataEG))[1]
	
	# ADaM-like: reference range as defined in SAP
	varsECGRange <- c("ANRLO", "ANRHI")
	if(any(varsECGRange %in% colnames(dataEG))){
		varExtra <- setdiff(varsECGRange, colnames(dataEG))
		# ECG often doesn't have a lower limit
		if(length(varExtra) > 0)	dataEG[[varExtra]] <- c(-Inf, +Inf)[match(varExtra, varsECGRange)]
		paramValueRangeVarEG  <- varsECGRange
	}else	paramValueRangeVarEG <- NULL
	
	paramVarEG <- varsEG
	timeVarEG <- intersect(c("ADY", "EGDY"), colnames(dataEG))[1]
	
	paramGroupVarEG <- intersect(c("EGCAT", "EGSCAT"), colnames(dataEG))
	if(length(paramGroupVarEG) == 0)	paramGroupVarEG <- NULL
	
	colorVarEG <- shapeVarEG <- intersect("ANRIND", colnames(dataEG))[1]
	if(length(colorVarEG) > 0){
		
		idxEmpty <- which(dataEG[[colorVarEG]] == "")
		if(length(idxEmpty) > 0)
			dataEG[idxEmpty, colorVarEG] <- "Unknown"
		levels <- unique(dataEG[[colorVarEG]])
		# add extra elements if present
		xStandard <- intersect(names(colorPaletteRind), levels)
		xExtra <- setdiff(na.omit(levels), names(colorPaletteRind))
		if(length(xExtra) > 0)
			warning("Flag variable contain non-standard elements:", toString(xExtra), ".")
		levels <- c(xStandard, xExtra)
		shapePaletteEG <- c(shapePaletteRind[xStandard], setNames(seq_along(xExtra), xExtra))
		colorPaletteEG <- c(colorPaletteRind[xStandard], setNames(seq_along(xExtra), xExtra))
		dataEG[[colorVarEG]] <- factor(dataEG[[colorVarEG]], levels = levels)
		
	}else	colorVarEG <- shapeVarEG <- colorPaletteEG <- shapePaletteEG <- NULL
		
	hasEGData <- !is.null(dataEG) && 
		length(paramVarEG) > 0 && length(paramValueVarEG) > 0 &&
		length(timeVarEG) > 0
	if(hasEGData){
		patientProfileModules <- c(patientProfileModules, "eg")
	}else{
		warning("Patient profiles not created for electrocardiogram, because of missing variables.")
	}
	
```

```{r patientProfiles-createPatientProfiles-eg, eval = "eg" %in% patientProfileModules}
	egPlots <- subjectProfileLinePlot(
		data = dataEG,
		paramValueVar = paramValueVarEG,
		paramNameVar = paramVarEG,
		paramValueRangeVar = paramValueRangeVarEG,
		paramGroupVar = paramGroupVarEG,
		timeVar = timeVarEG,
		colorVar = colorVarEG, colorPalette = colorPaletteEG,
		shapeVar = shapeVarEG, shapePalette = shapePaletteEG,
		shapeSize = 4,
		labelVars = labelVars,
		title = "Electrocardiogram",
		subjectSubset = subjectSubset,
		alpha = 0.8
	)
	patientProfilesPlots <- c(patientProfilesPlots, list(EG = egPlots))
```

## Creation of the subject profiles

```{r patientProfiles-createSubjectProfileReport, message = TRUE, warning = TRUE}

# dataset used to sort the subjects for the export
subjectSortData <- if(!is.null(params$subjectSortDataset))
	dataAll[[params$subjectSortDataset]]

pathsPatientProfiles <- createSubjectProfileReport(
	listPlots = patientProfilesPlots, 
	reportPerSubject = TRUE, 
	verbose = TRUE,
	outputFile = params$outputFile,
	timeAlign = "all", timeAlignPerSubject = "all",
	exportBatchSize = params$exportBatchSize,
	subjectSortData = subjectSortData,
	subjectSortVar = params$subjectSortVar,
	subjectSortDecreasing = params$subjectSortDecreasing
)

```

# Session information

```{r sessionInformation}

	library(pander)
	pander(sessionInfo())

```