<!--- 
This report create a scatterplot of a dataset and variables of interest.

Input parameters:
 
* Report-specific
- reportTitle: string with report title
- reportTitleLevel: integer with level of the report title, 1 for chapter, 2 for section, ...
- dataFileName: string with name of the file of interest
- dataProcessing (optional): list with parameters for data processing, see ? medicalMonitoring::processData
- loopingVar (optional): character vector with variables to loop over, a plot will be created for each combination of groups of this variable
- loopingNMax (optional): integer with maximal number of groups to consider (all by default)
- plotFunction: string with name of a plotting function of interest, available in the medicalMonitoring package
- plotParams: list with plotting parameters passed to the 'plotFunction' function
(excepted: 'data', 'labelVars', 'table', 'pathVar', 'id' and 'verbose')

* General:
- pathDataFolder: string with path to the data folder
- patientProfilePath: string with relative path where patient profiles are stored

-->

```{r medicalMonitoringPlotTemplate-options, echo = FALSE, warning = FALSE, message = FALSE}

library(knitr)
opts_chunk$set(
	echo = FALSE, 
	warning = FALSE, error = FALSE, message = FALSE, 
	results = "asis"
)

knitr::knit_hooks$set(
	message = function(x, options) {
		paste('\n\n<div class="alert alert-info">',
			gsub('##', '\n', x),
			'</div>', sep = '\n')
	}
)

# print warnings where they occur (warn = 0 by default)
options(warn = 1)

```

```{r medicalMonitoringPlotTemplate-attachParameters}

# Note: find a way to specify defaults for variables
attach(params)
if(!exists("loopingVar")) loopingVar <- NULL
if(!exists("comparisonTableType"))	comparisonTableType <- "none"
if(!exists("patientProfilePath"))	patientProfilePath <- NULL

```

```{r medicalMonitoringPlotTemplate-loadPackages}

library(medicalMonitoring)
library(glpgUtilityFct)
library(plyr)

```

```{r medicalMonitoringPlotTemplate-setTitle}

if(!exists("reportTitleLevel"))	reportTitleLevel <- 1

# Create a header at the wanted depth
cat(getMdHeader(title = reportTitle, level = reportTitleLevel))

```


```{r medicalMonitoringPlotTemplate-getData}

# Load data
if(comparisonTableType != "none") {
	
	if(!exists("pathDataFolderOld"))	stop("'pathDataFolderOld' should be specified.")
	
	pathsData <- c(
		"currentData" = pathDataFolder,
		"previousData" = pathDataFolderOld
	)	
	
} else pathsData <- c("currentData" = pathDataFolder)

dataList <- sapply(names(pathsData), function(dataBatch) {
			
	pathData <- file.path(
		pathsData[[dataBatch]],
		dataFileName
	)
	
	dataAll <- loadDataADaMSDTM(pathData, verbose = FALSE)
	data <- dataAll[[1]]
	
	# Extract label information
	labelVars <- attr(dataAll, "labelVars")
	
	# Data processing 
	if(exists("dataProcessing")){
		data <- processData(
			data = data, 
			dataPath = pathDataFolder,
			processing = dataProcessing,
			verbose = TRUE,
			labelVars = labelVars
		)
		# Labels updated with extra annotation:
		labelVars <- attr(data, "labelVars")
	}
	
	# Create URL to patient profiles
	if(!is.null(patientProfilePath))
		data <- createPatientProfileVar(
			data = data, 
			patientProfilePath = patientProfilePath,
			checkExist = FALSE
		)
	
	data
	
}, simplify = FALSE)

data <- dataList$currentData
labelVars <- attr(dataList$currentData, "labelVars")

```

```{r medicalMonitoringPlotTemplate-createTable, eval = (FALSE & comparisonTableType != "none")}

previousData <- dataList$previousData
if(!exists("comparisonTableParams"))	comparisonTableParams <- NULL
## By default, reference variables is the USUBJID
if(is.null(comparisonTableParams$referenceVars))
	comparisonTableParams$referenceVars <- "USUBJID"
## By default: changeable variables are the variables of the plot
if(is.null(comparisonTableParams$changeableVars)){
	comparisonTableParams$changeableVars <- c(
		plotParams$xVar,
		plotParams$yVar,
		plotParams$aesPointVar$colour
	)
}


argsCompTable <- c(
	list(
		newData = dataList$currentData,
		oldData = dataList$previousData,
		outputType = comparisonTableType,
		checkExistPatientProfilePath = FALSE
	),
	comparisonTableParams
)
outputComparison <- do.call(compareTables, argsCompTable)

if(!is.null(outputComparison)){
	
	data <- outputComparison

	tableVars <- c(argsCompTable$referenceVars, argsCompTable$changeableVars, "Type")
	labelVars["Type"] <- "Type of change from previous data"
	# What to do if tableVars is already specified?
	plotParams$tableVars <- tableVars
	
}

```

```{r medicalMonitoringPlotTemplate-createPlot}

if(!is.null(loopingVar)){
	
	data[, loopingVar] <- colwise(function(x) gsub("\\.", "", x))(data[, loopingVar, drop = FALSE])
	
	# only subset of the data if requested in _bookdown.yml
	if(exists("loopingNMax") &&	is.integer(loopingNMax)){
		
		data <- merge(
			x = data,
			y = unique(data[, loopingVar, drop = FALSE])[seq_len(loopingNMax), , drop = FALSE],
			all = FALSE
		)
		
	}
	
}

listPlots <- dlply(data, loopingVar, function(dataI){
			
	# Create plot unique ID
	argsFormatLabelChunk <- c(
		list("medicalMonitoringPlotTemplate-createPlot"),
		if(!is.null(loopingVar))	unique(dataI[, loopingVar, drop = FALSE])
	)		
	id <- do.call(formatLabelChunk, argsFormatLabelChunk)
	
	# Create the plot
	message("Create plot: ", id)
	inputParamsI <- c(
		plotParams, 
		list(
			data = dataI, labelVars = labelVars, 
			table = TRUE,
			pathVar = if(!is.null(patientProfilePath))	"patientProfilePath",
			id = id,
			verbose = TRUE
		)
	)
	do.call(plotFunction, inputParamsI)		
})

knitPrintMedicalMonitoring(
	list = listPlots,
	level = reportTitleLevel + 1
)

```
