# Report-specific parameters
template: countsVisualizationTemplate.Rmd
templatePackage: clinDataReview
reportTitle: "Enrollment by country and site"
reportTitleLevel: 2

# Dataset of interest
dataFileName: "dm.xpt"
dataProcessing:
  - filter:
    # safety analysis set: treated-patients
    - var: "RFXSTDTC" 
      value: ""
      rev: true

# Parameters to define counts of interest
countVar: "ARM"
parentVar: ["COUNTRY","SITEID"]
typePlot: [treemap]
