# Report-specific parameters
template: listingTemplate.Rmd
templatePackage: clinDataReview
reportTitle: "Concomitant medications listing"
reportTitleLevel: 2

# Dataset of interest
dataFileName: cm.xpt
dataProcessing:
  - annotate:
    - dataset: dm
      vars: ["RFXSTDTC"] 
  - filter:
    # safety analysis set: treated-patients
    - var: "RFXSTDTC" 
      value: ""
      rev: true

# Table parameters
tableParams:
  tableVars:
    - "USUBJID"
    - "CMDECOD"
    - "CMDOSE"
    - "CMDOSU"
    - "CMROUTE"    
    - "CMCLAS"
    - "VISIT"
    - "CMSTDTC"
    - "CMSTDY"
    - "CMENDTC"
    - "CMENDY"
    - "CMINDC"
  tablePars:
    buttons: !r clinUtils::getClinDTButtons(typeExtra = "colvis", opts = list(pdf = list(orientation = "landscape")))
  
